- CHANGELOG.md
- mockall/src/lib.rs
- mockall/tests/automock_generic_arguments_with_where_clause.rs
- mockall/tests/mock_generic_constructor_with_where_clause.rs
- mockall/tests/mock_generic_method_with_where_clause.rs
- mockall/tests/mock_generic_static_method_with_where_clause.rs
- mockall/tests/mock_specializing_methods.rs
- mockall_derive/src/expectation.rs
- mockall_derive/src/lib.rs
* Correctly handle where clauses on mocked methods.
* Handle generic specializing methods
* Document workaround for nongeneric specializing methods
> Where clauses

- CHANGELOG.md
- mockall/src/lib.rs
- mockall/tests/mock_reference_arguments.rs
- mockall/tests/mock_return_reference.rs
- mockall/tests/mock_struct.rs
- mockall/tests/mock_struct_with_static_method.rs
- mockall_derive/src/expectation.rs
times_any and times_range are now deprecated, because their
functionality has been merged with times.  This should be easier for
users to remember.  This syntax is inspired by Mockiato.
> The times method now accepts range arguments

- CHANGELOG.md
- mockall/src/lib.rs
- mockall/tests/automock_generic_struct_with_static_method.rs
- mockall/tests/mock_generic_constructor.rs
- mockall/tests/mock_generic_constructor_with_where_clause.rs
- mockall/tests/mock_generic_struct_with_generic_static_method.rs
- mockall_derive/src/expectation.rs
- mockall_derive/src/lib.rs
- mockall_derive/src/mock.rs
Eliminate the hack for static methods of generic structs whereby the method must repeat the struct's generic parameters in the method definition.
> Static generics

- CHANGELOG.md
- mockall/src/lib.rs
- mockall/tests/automock_specializing_methods.rs
- mockall_derive/src/lib.rs
> Specializing methods can now be seamlessly mocked

- CHANGELOG.md
- mockall/tests/automock_constructor_in_generic_trait.rs
- mockall_derive/src/expectation.rs
- mockall_derive/src/lib.rs
It's now possible to automock methods of a generic struct or trait that
reference `Self`.
Fixes #17
> Fix deselfify to work with generic structs

- CHANGELOG.md
- mockall/tests/automock_generic_constructor.rs
- mockall_derive/src/automock.rs
- mockall_derive/src/expectation.rs
- mockall_derive/src/lib.rs
- mockall_derive/src/mock.rs
Now it's possible to automock generic constructor methods
Fixes #23
> Fix mocking generic methods that use Self

- mockall/tests/mock_struct_with_static_method.rs
- mockall_derive/src/automock.rs
- mockall_derive/src/expectation.rs
- mockall_derive/src/mock.rs
Previously, a failed checkpoint would trigger a panic with a Mutex held,
poisoning that Mutex and possibly causing future tests to fail.  Now,
the panic will be deferred until after the Mutex gets released,
preventing any poison.
Fixes #7
> Panic more gracefully when a static method's checkpoint fails

- CHANGELOG.md
- mockall/tests/automock_associated_type_constructor.rs
- mockall_derive/src/lib.rs
This is especially important for constructors that return impl
Future<Type=Self,...>
> Fix deselfify for trait objects with associated types

- CHANGELOG.md
- README.md
- mockall/src/lib.rs
- mockall_derive/Cargo.toml
- mockall_derive/src/expectation.rs
- mockall_examples/Cargo.toml
It will no longer be necessary for users to explicitly depend on
Fragile, downcast, and predicates-tree.
> Reexport more stuff from the main crate

- CHANGELOG.md
- mockall/src/lib.rs
- mockall/tests/mock_return_mutable_reference.rs
- mockall/tests/mock_return_reference.rs
- mockall/tests/mock_struct.rs
- mockall/tests/mock_struct_with_static_method.rs
- mockall_derive/src/expectation.rs
When the nightly feature is enabled, methods whose return values aren't
explicitly set will return a default value, if the type implements
Default.  This feature has now been extended to methods returning
references to types that implement Default.
> Support returning default values for methods returning references

- CHANGELOG.md
- mockall/src/lib.rs
- mockall/tests/mock_reference_arguments.rs
- mockall/tests/mock_return_reference.rs
- mockall/tests/mock_struct.rs
- mockall/tests/mock_struct_with_static_method.rs
- mockall_derive/src/automock.rs
- mockall_derive/src/expectation.rs
- mockall_derive/src/mock.rs
The panic messages for a failed call counts panic will now include the
name of the method.
Fixes #31
> Better panic messages for failed call counts

- CHANGELOG.md
- mockall/tests/mock_generic_struct_with_generic_static_method.rs
- mockall/tests/mock_generic_struct_with_nondefault_parameter.rs
- mockall/tests/mock_return_mutable_reference.rs
- mockall/tests/mock_return_reference.rs
- mockall/tests/mock_struct.rs
- mockall/tests/mock_struct_with_static_method.rs
- mockall_derive/src/expectation.rs
- mockall_derive/src/mock.rs
There's no good reason to create a Context object but not set any
expectations.  And when the "nightly" feature is off, there's no good
reason to create an expectation but not set its return value.  Warn the
user if he does one of those things.
Suggested by @ArekPiekarz
> Add some must_use warnings

- CHANGELOG.md
- mockall/tests/automock_deref.rs
- mockall_derive/src/expectation.rs
Don't perform the deref conversion when mocking methods that return
&'static references
Fixes #38
> Fix mocking methods that return &'static str

- CHANGELOG.md
- mockall/src/lib.rs
- mockall/tests/automock_foreign_c.rs
- mockall/tests/automock_module.rs
- mockall/tests/automock_slice_arguments.rs
- mockall/tests/mock_generic_arguments.rs
- mockall/tests/mock_generic_struct_with_generic_static_method.rs
- mockall/tests/mock_struct.rs
- mockall/tests/mock_struct_with_static_method.rs
- mockall_derive/src/automock.rs
- mockall_derive/src/expectation.rs
- mockall_derive/src/mock.rs
"No matching expectation found" panic messages now include the method name.
> Better panics2

- CHANGELOG.md
- mockall/tests/automock_foreign_c.rs
- mockall/tests/automock_module.rs
- mockall/tests/mock_generic_struct_with_generic_static_method.rs
- mockall/tests/mock_struct_with_static_method.rs
- mockall_derive/src/expectation.rs
Fix `return_const` for static methods
> Fix `return_const` for static methods

- CHANGELOG.md
- mockall/src/lib.rs
- mockall/tests/automock_generic_method_with_lifetime_parameter.rs
- mockall/tests/mock_generic_method_with_lifetime_parameter.rs
- mockall/tests/mock_static_method_with_lifetime_parameters.rs
- mockall_derive/src/automock.rs
- mockall_derive/src/expectation.rs
- mockall_derive/src/lib.rs
- mockall_derive/src/mock.rs
Now it's possible to mock generic methods with lifetime parameters, as long as they don't also have type parameters, and their return values are `'static` or have the same lifetime as `self`.
@michaelmarconi does this work for you?
> Allow mocking generic methods with lifetime parameters

- mockall_derive/src/automock.rs
automock can only mock inline modules (like `mod foo{...}`), not modules
from another file, like `mod foo;`.
Fixes #49
> Print an error message if the user tries to mock an external module

- CHANGELOG.md
- mockall/tests/automock_module_nonpub.rs
- mockall_derive/src/automock.rs
- mockall_derive/src/expectation.rs
- mockall_derive/src/lib.rs
- mockall_derive/src/mock.rs
> Fix using super:: in the signature of a bare function with automock

- mockall/src/lib.rs
- mockall_derive/src/lib.rs
Previous versions of rustdoc did not allow adding doc comments to a
reexported proc macro, so mockall had to document fake locally-defined
macros with the same names as mockall_derive's proc macros.
That limitation is fixed as of rustc 1.40.0-nightly (084beb83e
2019-09-27), so we can remove the hack and put the doc comments where
they belong.
Fixes #42
> Unhack proc macros' doc comments

- CHANGELOG.md
- mockall/Cargo.toml
- mockall_derive/Cargo.toml
- mockall_derive/src/expectation.rs
- mockall_derive/src/lib.rs
- mockall_derive/src/mock.rs
Pull request #37 added some must_use warnings conditionalized on the
"nightly" feature.  However, because proc macros are unhygienic, the
warnings were actually conditionalized on the instantiating crate's
nightly feature, not on mockall_derive's nightly feature.  I didn't
notice at the time because Mockall _also_ has a nightly feature, and so
does the only crate of mine that uses Mockall.
Fix the hygiene errors, and rename mockall_derive's feature to
"nightly_derive", which will help to catch similar errors in the future.
> Fix hygiene violations in some warnings

- mockall_derive/src/expectation.rs
`an_array.into_iter()` currently just works because of the autoref
feature, which then calls `<[T] as IntoIterator>::into_iter`. But
in the future, arrays will implement `IntoIterator`, too. In order
to avoid problems in the future, the call is replaced by `iter()`
which is shorter and more explicit.
A crater run showed that your crate is affected by a potential future 
change. See https://github.com/rust-lang/rust/pull/65819 for more information.
> Use `slice::iter` instead of `into_iter` to avoid future breakage

- CHANGELOG.md
- mockall/src/lib.rs
- mockall/tests/mock_generic_struct_with_generic_static_method.rs
- mockall/tests/mock_struct_with_static_method.rs
- mockall_derive/src/mock.rs
This behavior is more useful where static and regular methods are both
used in the same test.  The old behavior was a relic from release 0.3.0
and before, when static methods did not yet have Context objects of
their own.
This commit also fixes intermittent test failures in
mock_generic_struct_with_generic_static_method and
mock_struct_with_static_method.  Those tests were failing because the
mock objects' checkpoints from one test were unexpectedly interfering
with static methods expectations' from other tests.
> Mock objects' checkpoint methods no longer check static expectations.

- mockall/src/lib.rs
Unfortunately little of this test actually gets executed because doc
tests are always built without #[cfg(test)]
> Fix the syntax in the doc test for mocking modules

- CHANGELOG.md
- mockall/tests/automock_custom_result.rs
- mockall_derive/src/expectation.rs
There was a hygiene violation in the proc macro.  It would cause
automock and mock to fail anytime a custom Result type was in scope,
even if the mocked method didn't try to use it.
Fixes #73
> Fix mocking methods when a custom Result type is in-scope

- CHANGELOG.md
- mockall/Cargo.toml
- mockall/tests/mock_unsized.rs
This fixes using `predicate::{always, never}` with `?Sized` types.
Fixes #78
> Update predicates to 1.0.2

- CHANGELOG.md
- mockall/src/lib.rs
- mockall/tests/mock_generic_method_returning_nonstatic.rs
- mockall_derive/src/automock.rs
- mockall_derive/src/expectation.rs
- mockall_derive/src/lib.rs
- mockall_derive/src/mock.rs
mock generic methods returning non-static values
It's now possible to mock generic methods whose return values' lifetimes are
chosen by the caller.  This is especially useful for methods that return
std::future::Future.
There are presently two restrictions:
1) static methods and bare functions of this type are not supported
2) The expectations' return values must be 'static.  That can often be
worked-around via an unsafe lifetime transmute.
Hopefully both of those restrictions will be lifted in time.
Fixes #76
> mock generic methods returning non-static values

- mockall/tests/automock_generic_method_with_bounds.rs
- mockall_derive/src/expectation.rs
generic struct with type bounds on their struct's generic parameters
that also have generic methods are probably affected.
Fixes #88
> Fix regression mocking generic methods with type bounds

- mockall/src/lib.rs
.in_sequence should normally be used with .times
> Slightly improve the overall docs for Sequence

- CHANGELOG.md
- mockall/src/lib.rs
- mockall/tests/automock_nonsend.rs
- mockall_derive/src/expectation.rs
> Implement `with_st` to match non-`Send` arguments.

- CHANGELOG.md
- mockall/tests/mock_docs.rs
- mockall_derive/src/automock.rs
- mockall_derive/src/mock.rs
Previously, the build would fail if the mock struct line contained a doc
comment.  Now, the build will pass, and doc comments on the struct and
methods will be propagated to the generated code.
Fixes #100
> Allow doc comments in mock! macro

- .cirrus.yml
- CHANGELOG.md
- README.md
- mockall/Cargo.toml
This fixes runtime errors with the latest nightly compiler, 2020-03-11
or later, which are stricter about uninitialized data.
> Update Fragile to 1.0

- CHANGELOG.md
- mockall/tests/automock_nonstatic_struct.rs
- mockall_derive/src/expectation.rs
- mockall_derive/src/lib.rs
- mockall_derive/src/mock.rs
Constructor methods are not yet supported.
Fixes #4
The gory details:
* Generics of mock structs should not include lifetimes
* deselfify before split lifetimes
* Include rlifetimes in some impl blocks
* Include some missing <> in an intermediate Generics object
* Fix deselfify with lifetimes
* Handle apparently unused lifetimes in  split_lifetimes
* Fix determination of whether a method is generic in method_types.  There was
some leftover logic from back when all methods of generic structs were
treated as generic methods.
* Remove lifetimes from Context objects
> Allow mocking non-'static structs

- mockall_derive/src/lib.rs
This PR fixes the following warning caused by not using the returned
value from `mem::replace`.
```
warning: unused return value of `std::mem::replace` that must be used
--> mockall_derive/src/lib.rs:519:21
|
519 |                     mem::replace(bt, new_bt);
|                     ^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_must_use)]` on by default
= note: if you don't need the old value, you can
just assign the new value directly
warning: 1 warning emitted
```
> Fix mem::replace warning

- CHANGELOG.md
- mockall/tests/automock_attrs.rs
- mockall_derive/src/automock.rs
- mockall_derive/src/lib.rs
- mockall_derive/src/mock.rs
Fix mocking functions with attributes
When mocking methods, we forward all non-doc attributes to the mock method.  This commit ensures that we do the same for foreign functions and module functions.  It allows, for example:
```rust
#[automock]
extern "C" {
#[cfg(target_os = "linux")]
fn linux_func();
#[cfg(target_os = "freebsd")]
fn freebsd_func();
}
```
> Fix mocking functions with attributes

- CHANGELOG.md
- mockall/tests/automock_foreign_nonpub.rs
- mockall/tests/automock_module_nonpub.rs
- mockall_derive/src/automock.rs
- mockall_derive/src/lib.rs
* When mocking foreign functions, the 'foreign "<ABI>"' block is not a
module, and should not introduce an extra layer of visibility
modifications.
* The visibility of the Expectation must always match the levels
argument of Expectation::new().
* When mocking modules, the argument and return types of mocked
functions must be superfied by one level.  Otherwise code like this
wouldn't compile:
```rust
struct SuperT;
#[automock]
pub mod m {
fn foo(x: super::SuperT) -> super::SuperT;
}
```
> Fix some visibility issues with mocking modules and foreign functions:

- mockall_derive/src/mock.rs
This reduces diffs between methods, and helps simplify the 2020_refactor
implementation.
> deselfify mock methods, not just expectations

- CHANGELOG.md
- mockall_derive/src/lib.rs
Examples of methods that would be mocked incorrectly include:
```
fn foo(&self, x: [super::T]);
fn bar(&self) -> (super::T, i32);
```
This is a bug that was introduced by
697d341d7cd622e8ba4bf15cb15f6cacbb76220a.  That revision correctly
handled `super` when it appeared in `Path` and `TraitObject` types, but
not more complicated types.
> Fix mocking methods with types including a `super::` component

- mockall_derive/src/lib.rs
- mockall_derive/src/mock.rs
Previously, Mockall would often duplicate the bounds in Generics fields,
both in the parameter list and in the where clause.  Counterintuitively,
it even did that when one of the two Generics being merged was empty.
This simple change fixes most duplication, but it's still possible where
the two Generics have partially overlapping bounds.
AFAIK this bug never prevented any mocks from compiling.  Rust dutifully
accepts duplicate Generics bounds.
> Reduce duplication in merged Generics

- CHANGELOG.md
- mockall/tests/automock_generic_static_method.rs
- mockall_derive/src/expectation.rs
This was left out of PR #47 as an oversight.  That PR only fixed
return_const for non-generic static methods.
> Fix return_const on mocked generic static methods

- mockall_derive/Cargo.toml
- mockall_derive/src/mock.rs
When mock! fails due to unsupported items in the struct section, print a
better error message, including the span.
Issue #143
> Better error messages with mock!

- mockall_derive/src/expectation.rs
* Change the order of generated methods for static expectation guards. The new order makes no difference to behavior but eases the 2020_refactor branch.
* Diff reduction between generated code for static methods.  Use consistent formatting for generic and non-concrete static methods
> Minor refactor4

- mockall_derive/src/mock_function.rs
- mockall_derive/src/mock_item.rs
- mockall_derive/src/mock_item_struct.rs
- mockall_derive/src/mockable_item.rs
Previously Mockall would deliberately generate some `-> ()` return types,
due to the legacy of the expectation! macro.  This commit removes all of
those.  However, there are still a few `-> () + <trait bound>` types in
the generated code.  Those are too much trouble to eliminate, so we
suppress the clippy warning instead.
Fixes #149
> Don't generate as many -> () return types

- mockall_derive/src/mock_function.rs
- mockall_derive/src/mock_item.rs
- mockall_derive/src/mock_item_struct.rs
The doc strings in question have always been wrong.
> Fix some comments and doc strings in the generated code

- CHANGELOG.md
- mockall/src/lib.rs
Rust's specialization feature is considered incomplete, and recent
compilers print a warning if you try to use it.  But we know that it's
unstable; that's why it's guarded by the "nightly" flag.
> Disable the warning for incomplete features

- CHANGELOG.md
- mockall/tests/automock_module.rs
- mockall/tests/automock_module_nonpub.rs
- mockall_derive/src/mockable_item.rs
1) methods that return "impl Trait" wouldn't work
2) methods that use mutable arguments would spew warnings
3) The mock module had too generous visibility.
> Fix three issues with mocking modules

- CHANGELOG.md
- mockall/tests/automock_trait_object.rs
- mockall_derive/src/mockable_struct.rs
Such arguments can be matched with `withf`.  However, `with` is useless
for such arguments, because it isn't possible to construct a useful
Predicate that works with them.  That's unlikely to change in future
versions of Mockall.
Fixes #152
> Support mocking methods with trait object arguments

- CHANGELOG.md
- mockall/tests/mock_box_self.rs
- mockall_derive/src/lib.rs
- mockall_derive/src/mock_function.rs
> Allow mocking methods with complicated receivers like self: Box<Self>

- mockall/tests/automock_constructor_in_generic_trait.rs
- mockall/tests/automock_constructor_in_trait_with_args.rs
- mockall/tests/automock_generic_constructor.rs
- mockall/tests/automock_generic_static_method.rs
- mockall/tests/automock_generic_struct_with_static_method.rs
- mockall/tests/automock_nonsend.rs
- mockall/tests/automock_static_method.rs
- mockall/tests/mock_multiple_traits.rs
- mockall_derive/src/mock_item_struct.rs
Eliminates "error: field is never read" warnings
Fixes #177
> Generate less code when mocking traits with no non-static methods

- CHANGELOG.md
- mockall/Cargo.toml
- mockall/src/lib.rs
- mockall/tests/automock_async_trait.rs
- mockall/tests/mock_async_fn.rs
- mockall/tests/mock_async_trait.rs
- mockall/tools/allgen.sh
- mockall/tools/gen.sh
- mockall_derive/src/lib.rs
- mockall_derive/src/mock_function.rs
- mockall_derive/src/mock_item_struct.rs
- mockall_derive/src/mock_trait.rs
Now it's possible to mock! or automock an async_trait, with no extra effort.
Fixes #75
> async_trait compatibility

- CHANGELOG.md
- mockall/src/lib.rs
- mockall/tests/automock_deref.rs
- mockall_derive/src/mock_function.rs
When setting expectations, use the owned form: a Vec.
Fixes #130
> Allow mocking methods that return slices

- CHANGELOG.md
- mockall/src/lib.rs
- mockall/tests/automock_associated_const.rs
- mockall/tests/mock_associated_const.rs
- mockall_derive/src/mock_item_struct.rs
- mockall_derive/src/mock_trait.rs
- mockall_derive/src/mockable_struct.rs
automock can now mock a trait impl with an associated const.  It can't
mock the trait declaration, because in that case there's no way to set
the value of the associated const on the mock struct.  Of course, if the
trait itself has a default value for the const, then automock will work.
automock can now mock a struct impl with an associated const.
mock! can now mock structs with both inherent associated consts, and
associated consts on their trait impls.
Fixes #97
> Add support for mocking associated consts

- CHANGELOG.md
- mockall/src/lib.rs
- mockall/tests/automock_attrs.rs
- mockall/tests/automock_module.rs
- mockall/tests/automock_module_nonpub.rs
This is a new unannounced feature in Rust 1.42.0.
> proc_macro_hygiene is no longer needed to automock modules

- .cirrus.yml
- mockall/src/lib.rs
Previously we only denied all warnings during unit tests.  This denies
them during the regular build too, but only during CI.
> Deny all warnings during CI

- Cargo.toml
- mockall/Cargo.toml
- mockall/examples/ffi.rs
- mockall/src/lib.rs
- mockall_derive/Cargo.toml
- mockall_double/Cargo.toml
- mockall_double/README.md
- mockall_double/src/lib.rs
- release.toml
Add mockall_double, a handy double adapter.
It makes it easier to import Mockall's mocked structs and modules.
Basically, it replaces cfg-if, and turns 6 lines into 1.
Fixes #71
Also, improve release procedure
* Automatically update CHANGELOG.md
* Don't generate tags for mockall_derive
* Name tags "vX.Y.Z" instead of "mockall-vX.Y.Z"
* Do fewer git pushes
The procedure for mockall_double is unchanged, because it's expected
that mockall_double won't have its releases synchronized with the other
crates.
> Add Mockall double

- CHANGELOG.md
- mockall/src/lib.rs
- mockall/tests/mock_associated_const.rs
- mockall/tests/mock_associated_types.rs
- mockall/tests/mock_async_trait.rs
- mockall/tests/mock_clone.rs
- mockall/tests/mock_concrete_struct_with_generic_trait.rs
- mockall/tests/mock_docs.rs
- mockall/tests/mock_generic_arguments_returning_reference.rs
- mockall/tests/mock_generic_struct_with_generic_trait_oldstyle.rs
- mockall/tests/mock_generic_struct_with_generic_trait_with_different_bounds.rs
- mockall/tests/mock_generic_struct_with_nondefault_parameter.rs
- mockall/tests/mock_generic_struct_with_trait.rs
- mockall/tests/mock_generic_struct_with_trait_with_associated_types.rs
- mockall/tests/mock_generic_struct_with_where_clause_and_trait.rs
- mockall/tests/mock_generic_trait.rs
- mockall/tests/mock_inherited_traits.rs
- mockall/tests/mock_multiple_traits.rs
- mockall/tests/mock_nonlocal_trait.rs
- mockall/tests/mock_return_anonymous_lifetime.rs
- mockall/tests/mock_struct_with_trait.rs
- mockall/tests/mock_struct_with_trait_with_associated_types.rs
- mockall/tests/mock_trait_returning_reference.rs
- mockall/tests/mock_trait_with_static_method.rs
- mockall_derive/src/mock_item_struct.rs
- mockall_derive/src/mock_trait.rs
- mockall_derive/src/mockable_struct.rs
Previously the syntax looked like a trait definition `trait X`.  But
that's ambiguous in the case of generic traits.  It doesn't make clear
the relationship between the trait's generic parameters and the struct's
generic parameters.  And it made it impossible for a concrete struct to
implement a generic trait.
The new syntax looks like a trait impl `impl X for Y`.  That solves all
the problems with generics.  In addition, it allows `mock!` to implement
traits that aren't imported directly into the current namespace
`impl x::y::Z for Foo`.
The old syntax is deprecated, but will be supported for at least one
more release.
Fixes #119
> Change mock!'s syntax for traits

- CHANGELOG.md
- mockall_derive/src/lib.rs
- mockall_derive/src/mockable_struct.rs
Previously, it forbade them, and treated the inherent method as having
the same visibility as the struct itself.  That was occasionally
problematic, for example when the mock struct was pub but one of its
methods' arguments was not.
Relates to issue #143
> `mock!` now requires visibility specifiers for inherent methods.

- CHANGELOG.md
- mockall/src/lib.rs
- mockall/tests/automock_qself.rs
- mockall_derive/src/lib.rs
- mockall_derive/src/mock_function.rs
In where clauses, this is a regression from 0.7.2.  But using qself in
return types never worked correctly.
> Fix using QSelf in a where clause or a return type.

- CHANGELOG.md
- mockall/src/lib.rs
- mockall/tests/mock_return_dyn_trait.rs
- mockall_derive/src/mock_function.rs
> Allow mocking methods thar return references to trait objects

- mockall_derive/src/mock_item_struct.rs
- mockall_derive/src/mockable_struct.rs
It's remarkable that the compiler accepts this without complaint.
Also, fix an incorrect comment from the same commit.  The
AngleBracketedGenericArguments will also be present when using automock
> Delete a weird copypasta from PR #205

- .cirrus.yml
- mockall_derive/src/mock_function.rs
We had been generating it, but not calling it, for non-generic methods
of generic structs.
> Don't generic unneeded GenericExpectation code

- CHANGELOG.md
- mockall/Cargo.toml
- mockall/tests/automock_generic_future.rs
- mockall/tests/automock_generic_future_with_where_clause.rs
- mockall_derive/src/lib.rs
- mockall_derive/src/mock_function.rs
For example, generic structs implementing Future.  The method must not be treated as a generic method, since it has a non-static argument.
Issue #223
> Allow mocking methods with lifetime parameters of generic structs

- CHANGELOG.md
- mockall_derive/src/lib.rs
- mockall_derive/src/mock_function.rs
It turns out that it wasn't necessary.  PR #225 was sufficient to fix the issue.  And #226 is awkward, because it can result in the expect_ methods having fewer generic parameters than the original methods. Worse, sometimes mockall will generate code that fails to compile, because the Where clauses reference generic parameters that aren't there.
> Revert most of PR #226

- CHANGELOG.md
- mockall/src/lib.rs
- mockall/tests/automock_associated_type_constructor.rs
- mockall/tests/automock_impl_future.rs
- mockall_derive/src/lib.rs
Unlike other traits, these two aren't very useful in a `Box`.  Instead,
Mockall will now change the Expectation's return type to `Pin<Box<_>>`.
Fixes #220
> Automock methods returning "impl Future"

- CHANGELOG.md
- mockall/tests/mock_generic_return.rs
- mockall_derive/src/mock_function.rs
The return type was not being used to index into the Expectations
object. Probably I didn't do that to allow generic methods returning
references, because older versions of Mockall didn't already determine
the owned form of the return type.
Fixes #236
> Fix an issue with generic methods whose only generic type is the return

- CHANGELOG.md
- mockall/src/lib.rs
- mockall/tests/automock_foreign_c.rs
- mockall/tests/automock_foreign_extern.rs
- mockall/tests/automock_module.rs
- mockall/tests/automock_nondebug.rs
- mockall/tests/automock_slice_arguments.rs
- mockall/tests/mock_generic_arguments.rs
- mockall/tests/mock_generic_struct_with_generic_static_method.rs
- mockall/tests/mock_struct.rs
- mockall/tests/mock_struct_with_static_method.rs
- mockall/tests/mock_unsized.rs
- mockall_derive/src/mock_function.rs
When a method call has no matching expectation, it will now
print the arguments, if they implement Debug.  This requires the
"nightly" crate feature.
> Print better messages for "No matching expectation found"

- CHANGELOG.md
- mockall/src/lib.rs
- mockall/tests/mock_return_mutable_reference.rs
- mockall/tests/mock_return_reference.rs
- mockall/tests/mock_struct.rs
- mockall_derive/src/mock_function.rs
Print the method name and argument values during a method sequence
violation.  Argument values require the "nightly" feature, and the
arguments must implement Debug.
Fixes #241
> Better error messages for Sequence violations

- CHANGELOG.md
- mockall/Cargo.toml
- mockall/tests/automock_instrument.rs
- mockall_derive/src/lib.rs
The mock method won't be instrumented, but at least it will compile.
Fixes #253
> Add #[tracing::instrument] compatibility for #[automock]

- mockall_double/src/lib.rs
This seems to be used in the first page that's displayed on docs.rs, and every other usage in examples uses the correct syntax. This minor adjustment should make it less confusing for (other) new Rustaceans.
> corrected transposed letters

- mockall/tests/automock_extern_std.rs
- mockall_derive/src/mock_function.rs
In no_std libraries which import std as an extern crate, these two symbols need explicit importing.
Was having fun with my embedded µC and would like to add some unit tests. Found this nice mocking test library but found it a little annoying every time I have a "use mockall::*" I need to explicitly import the title-mentioned structs.
> Imports Box<> and Vec<> explicitly.

- mockall/src/lib.rs
The nightly feature is no longer required to mock modules.
> Fix the crate feature documentation after PR #198

- CHANGELOG.md
- mockall/tests/automock_generic_method_without_generic_args_or_return.rs
- mockall/tests/mock_closure.rs
- mockall_derive/src/lib.rs
- mockall_derive/src/mock_function.rs
If the function's generic parameters appeared in neither input nor
return type, the Expectations object would not be parameterized on the
functions generic parameters.  This wasn't really by design; it was
actually an artifact of Mockall's second incarnation, which used a
macro_rules! macro to generate the mock objects.
Fixing the problem is easy.  It's a matter of removing the code that
tried to guess the generic parameters based on the functions arguments
and return types.
Fixes #269
> Fix setting expectations on barely-generic functions

- CHANGELOG.md
- mockall/src/lib.rs
- mockall/tests/mock_generic_struct_with_generic_trait_with_different_bounds.rs
- mockall/tests/specific_impl.rs
- mockall_derive/src/automock.rs
- mockall_derive/src/lib.rs
- mockall_derive/src/mock_function.rs
- mockall_derive/src/mock_item_struct.rs
- mockall_derive/src/mock_trait.rs
- mockall_derive/src/mockable_struct.rs
A specific impl is an implementation of a trait on a generic struct with specific generic parameters, like `impl Foo for Bar<i32> {}`
Issue #271
> Support specific impls

- mockall_derive/src/lib.rs
- mockall_derive/src/mock_function.rs
These warnings only affect the proc-macro's internals, not generated
code.
> Pacify clippy-1.53.0

- mockall/tests/mock_same_trait_twice_on_generic_struct.rs
- mockall_derive/src/mock_item_struct.rs
- mockall_derive/src/mock_trait.rs
If the trait impl's self type has generic parameters, hash them.  This
allows implementing the same trait twice on a single struct, as long as
the specific generic parameters are different.  But for now, it also
requires that the mock struct is generic, limiting its usefulness.
> Use a less-predictable name for trait impls structs in generated code

- CHANGELOG.md
- mockall/src/lib.rs
- mockall/tests/automock_debug.rs
- mockall/tests/mock_debug.rs
- mockall_derive/src/lib.rs
- mockall_derive/src/mock_item_struct.rs
- mockall_derive/src/mockable_item.rs
- mockall_derive/src/mockable_struct.rs
Automatically generate Debug impls for mock structs.
Fixes #287
> Automatically generate Debug impls for mock structs

- CHANGELOG.md
- mockall/tests/mock_cfg.rs
- mockall_derive/src/mock_item_struct.rs
- mockall_derive/src/mock_trait.rs
mock! already allowed individual methods to be so gated.  Now it will
work for trait impls, too.
Fixes #288
> Allow #[cfg()] attributes on trait impls in mock!

- CHANGELOG.md
- mockall/tests/mock_generic_method_returning_nonstatic.rs
- mockall_derive/src/mock_function.rs
Must staticize return values for trait methods with generic arguments,
as long as the mock object itself is not generic.
This was a regression introduced by PR #274, and released in v0.10.0. It
only affects trait methods, not struct methods.
Fixes #298
> Fix mocking trait methods whose return values have lifetime parameters

- CHANGELOG.md
- mockall/tests/automock_specializing_method_of_nongeneric_struct.rs
- mockall_derive/src/lib.rs
Fix mocking specializing methods of non-generic structs
PR #272 added support for specializing methods of generic structs, but
broke specializing methods of nongeneric structs.
Fixes #307
> Fix mocking specializing methods of non-generic structs

- CHANGELOG.md
- mockall/tests/mock_generic_method_on_generic_struct_returning_nonstatic.rs
- mockall/tests/specific_impl.rs
- mockall_derive/src/mock_function.rs
> Fix mocking generic methods of generic structs returning nonstatic

- .cirrus.yml
This reverts commit 8f7efc98fffcabe1aba542ed59e60d3bdeca4a0b.
The Clippy bug has been fixed as of clippy 0.1.55 (74ef0c3e 2021-07-16)
> Revert "Suppress a buggy Clippy lint"

- mockall/src/lib.rs
- mockall/tests/automock_many_args.rs
- mockall/tests/mock_generic_struct_with_generic_static_method.rs
- mockall/tests/mock_reference_arguments.rs
- mockall/tests/mock_struct.rs
- mockall/tests/mock_struct_with_static_method.rs
- mockall_derive/src/mock_function.rs
Thanks for the crate! It's quite useful in a project of mine.
The `times()` method on a mock will assert that the expectation has been called a specific number of times.
Unfortunately, it does not print how many times it has been called! Only the expected count...
This makes it harder to diagnose what could have gone wrong in a test.
This PR adds the expectation call count to the panic message. For example:
```
MockFoo::baz: Expectation(<anything>) called 4 times which is more than expected 3
```
or
```
MockFoo::foo: Expectation(<anything>) called 0 time(s) which is fewer than expected 1
```
For this to work, I had to expose a new method `Times::count()`.
I left out any `Cargo.toml` version update as I am not sure of the project's policy on version. Let me know if a version bump is …
> Add count to error message

- CHANGELOG.md
- mockall/tests/automock_unsafe_trait.rs
- mockall/tests/mock_unsafe_trait.rs
- mockall_derive/src/mock_trait.rs
> Support unsafe traits

- mockall/tests/automock_gat.rs
No code changes are necessary to get this test working.
> Add a test for mocking Generic Associated Types

- .cirrus.yml
- mockall/tests/automock_multiple_lifetime_parameters.rs
- mockall_derive/src/lib.rs
mockall_derive was internally using HashMap and HashSet and iterating
over their contents.  But by default those types use random internal
state, resulting in nondeterministic output.  Switch them to use
consistent state.
Reported by:    David Tolnay @dtolnay
Also, add a CI check for nondeterminism.  When enabled, mock! and
#[automock] will evaluate every call twice and verify that the output is identical.
Also add a test case that is known to currently generate
non-reproducible output.  During CI, build the entire test suite with
this mode enabled.
> Fix nondeterministic code generation

- mockall/Cargo.toml
- mockall/src/lib.rs
This allows building mockall with warn(missing_docs)
Fxies #345
> Update downcast to 0.11.0

- mockall/examples/synchronization.rs
- mockall/src/lib.rs
just adds a link to the synchronization example in the main lib.rs doc
> docs: update docs with synchronization example

- .cirrus.yml
- mockall_derive/Cargo.toml
A recent upstream change has broken our tests on the MSRV, but not the
build itself.  Only run tests on stable and nightly.
> Don't run the tests on the MSRV in CI

- CHANGELOG.md
- mockall/tests/automock_partial_eq.rs
- mockall_derive/src/lib.rs
- mockall_derive/src/mockable_struct.rs
> Fix mocking methods that use `Self` in their arguments.

- mockall_double/CHANGELOG.md
- mockall_double/src/lib.rs
```rust
#[double]
type Foo = bar::Baz;
```
will become
```rust
#[cfg(not(test))]
type Foo = bar::Baz;
#[cfg(test)]
type Foo = bar::MockBaz;
```
> Add the ability to double type aliases to mockall_double

- CHANGELOG.md
- mockall/tests/mock_return_dyn_trait.rs
- mockall_derive/src/mock_function.rs
Continuation of #364. Resolves #363.
> [mockall-derive] Fix returning trait object reference for `Box<dyn T>` not implementing `T`

- CHANGELOG.md
- mockall/tests/anyhow.rs
- mockall_derive/src/mock_function.rs
The `anyhow` create defines a function by this name, and the proc-macro
generated code was picking it up instead of the standard Result::Ok .
Fixes #388
> Fix using Mockall when a function named `Ok` is in scope

- mockall/tests/automock_instrument.rs
- mockall/tests/automock_module_nonpub.rs
- mockall/tests/mock_associated_const.rs
- mockall/tests/mock_cfg.rs
- mockall/tests/mock_constructor_with_args.rs
- mockall/tests/mock_debug.rs
- mockall/tests/mock_docs.rs
- mockall/tests/mock_generic_method_on_generic_struct_returning_nonstatic.rs
- mockall/tests/mock_generic_method_returning_nonstatic.rs
- mockall/tests/mock_generic_struct_with_generic_static_method.rs
- mockall/tests/mock_life0.rs
- mockall/tests/mock_nonpub.rs
- mockall/tests/mock_refmut_arguments.rs
- mockall/tests/mock_struct_with_static_method.rs
- mockall_derive/src/lib.rs
- mockall_derive/src/mock_function.rs
- mockall_derive/src/mockable_item.rs
* clippy::explicit_auto_deref (but workaround clippy bug 9127)
* allow dead_code (in the tests)
* Remove some unneeded dead code in the tests
https://github.com/rust-lang/rust-clippy/issues/9127
> clippy cleanup

- CHANGELOG.md
- mockall/tests/automock_associated_const.rs
- mockall/tests/automock_foreign_c.rs
- mockall/tests/automock_instrument.rs
- mockall/tests/automock_nonpub_methods.rs
- mockall/tests/mock_cfg.rs
- mockall/tests/mock_docs.rs
- mockall/tests/mock_generic_struct_with_generic_static_method.rs
- mockall/tests/mock_life0.rs
- mockall/tests/mock_nonpub.rs
- mockall/tests/mock_struct_with_static_method.rs
- mockall_derive/src/mock_function.rs
It might be used only by other public methods in the same struct.
> Suppress "dead code" warnings when automocking a struct's private method

- .cirrus.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- mockall/Cargo.toml
- mockall/tests/automock_associated_const.rs
- mockall/tests/automock_gat.rs
* generic_associated_types is now stable on nightly
* futures-task raised its MSRV, so we must follow suit
* Fix an unused struct warning in one test with 1.45.0
* Add a rust-version field to Cargo.toml
> Fix tests with latest nightly compiler and latest deps

- CHANGELOG.md
- mockall/tests/automock_where_self.rs
- mockall_derive/src/lib.rs
- mockall_derive/src/mockable_struct.rs
Previously they were treated as generic.  Among other effects, this prevents "unused method expect" warnings from the latest nightly compiler.
Fixes #414
> Mock methods with `where Self: ...` clauses as concrete.

- mockall/Cargo.toml
Older ^1.0 versions of [fragile](https://crates.io/crates/fragile/versions) have been yanked from crates.io, leading to the following error.
```
error: failed to select a version for the requirement `fragile = "^1.0"`
candidate versions found which didn't match: 2.0.0
location searched: crates.io index
required by package `mockall v0.11.2`
... which satisfies dependency `mockall = "^0.11.2"` of package `[redacted] v0.0.0 ([redacted])`
```
> Bump fragile dependency due to yanked older versions

- Cargo.toml
This reverts commit a147af4cee2282b1dc793b7cecbcc7043d73b11e.
It's no longer needed now that itertools-1.15.0 is released.
> Revert "Patch itertools to fix the build on 1.45.0"

- mockall/src/lib.rs
If this warning was in the documentation it would have saved me a few hours.
> add static method caveat to Modules documentation

- .cirrus.yml
- CHANGELOG.md
- README.md
- mockall/Cargo.toml
Because our dependency predicates-tree did.
> Raise MSRV to 1.60.0

- mockall/tests/cfg_attr_concretize.rs
- mockall_derive/src/lib.rs
- mockall_derive/src/mock_function.rs
The concretize attribute isn't processed as a normal Rust attribute. Instead, Mockall processes it as text.  So we need to process any cfg_attr directive ourselves.  Rather than attempt to evaluate the conditional, just assume that it's true.  By far the most common use case will be `cfg_attr(test, concretize)`.
Fixes #427
> Correctly process the concretize attribute within cfg_attr

- mockall/tests/automock_generic_future_with_where_clause.rs
- mockall/tests/automock_where_self.rs
Yes, they're needless, but they're there to exercise Mockall's parsing.
> Suppress some needless_lifetimes warnings from Clippy

- CHANGELOG.md
- mockall/tests/clear_expectations_on_panic.rs
- mockall_derive/src/mock_function.rs
Even if a panic is in-progress.  Originally we didn't drop them during panic, for fear of double-panicing.  But there is already protection from double-panic in Common::drop.  Not clearing expectations during a panic can cause surprising failures in one test case after a different test case panics.
Fixes #442
> Always drop static methods' Expectations during Drop

- mockall/Cargo.toml
- mockall/src/lib.rs
- mockall_derive/Cargo.toml
- mockall_derive/src/lib.rs
- mockall_derive/src/mock_function.rs
- mockall_double/Cargo.toml
- mockall_double/src/lib.rs
It's especially useful to have the examples use 2021 edition, because that's what most new users will be using.
> Use 2021 edition throughout.

- mockall/tests/automock_generic_method_without_generic_args_or_return.rs
Suppress the extra_unused_type_parameters in a test, where it's intentional.
> Fix clippy

- mockall/examples/ffi.rs
`getuid()` is a clib function that's only available on UNIX systems, this pull request uses the `time()` function that's also available on Windows.
Now when running `cargo test` on Windows the command doesn't fail with error message:
```
error[E0601]: `main` function not found in crate `ffi`
--> mockall\examples\ffi.rs:35:2
|
35 | }
|  ^ consider adding a `main` function to `mockall\examples\ffi.rs`
```
> Changed example to use a C function available also on Windows

- CHANGELOG.md
The CHANGELOG was already correct in the r0.11 branch, but not on master.
[skip ci]
> Add v0.11.3 notes to CHANGELOG

- mockall_derive/Cargo.toml
- mockall_derive/src/lib.rs
- mockall_derive/src/mockable_struct.rs
This version of syn is more picky about parsing ItemImplFn.  Previously it would accept "pub fn foo(&self);" and consider the ";" to be the function's Block.  But now it (technically correctly) doesn't recognize that as a valid ItemImplFn.  So instead we'll have to parse that as a combination of a Visibility and a TraitItemFn.
> Fixing compatibility with syn-2.0.9

- CHANGELOG.md
- mockall/tests/mock_cfg.rs
- mockall/tests/mock_concretize.rs
- mockall_derive/src/mockable_struct.rs
Starting with syn 2.0.9, attempting to use an attribute on a non-private method would fail with a syntax error "expected fn".
Also, rename tim2iif to tif2iif.  This should've been part of the syn-2.0.0 conversion.
> Fix mock! with pub functions that have attrs with syn-2.0.9

- CHANGELOG.md
- clippy.toml
- mockall/tests/automock_seven_args.rs
- mockall_derive/src/mock_function.rs
This warning has always been possible, but it was particularly annoying when the user mocks a static function with seven arguments.  Because in that case, some of the generated code will have eight arguments, triggering the warning even though the original code did not.
Fixes #480
> Suppress clippy::too_many_arguments warnings in the generated code

- CHANGELOG.md
- mockall/tests/automock_foreign_c_variadic.rs
Add Test Scenario for C Variadics Using Mockall
This PR adds a test file to address the mocking of 'c_variadic' functions. However, please note that testing the variadic parameters themselves is not feasible due to their dynamic nature.
r @asomers
> Added C variadic test

- mockall_derive/src/lib.rs
The code genuinely was cloning too aggressively, copying more data than necessary.  Thanks, Clippy.
> Fix a clippy::unnecessary_cloned warning

- CHANGELOG.md
- mockall/tests/link_name.rs
- mockall_derive/src/lib.rs
Avoid emitting this attribute in the generated code, which causes `unused_attribute` warnings.
Fixes #502
> Work better with FFI functions that use `link_name`

- CHANGELOG.md
- mockall/Cargo.toml
Predicates has default optional features this crate doesn't use. These features even include regex, which is a heavy dependency. This PR should slightly improve compile times for crates using mockall
> Remove default features from predicates dependency

- CHANGELOG.md
- mockall/tests/clear_expectations_on_panic.rs
- mockall_derive/src/mock_function.rs
PR #443 ensured that static methods' expectations would be cleared on Drop.  But it was only tested for methods that paniced due to too few method calls.  For methods with too many calls it actually introduced a double-panic.  Double panics are bad; they lead to processes getting SIGABRT.  This was a regression in Mockall 0.11.4.
Fixes #491
> Fix a double-panic when static methods' expectations are oversatisfied

- mockall_derive/src/lib.rs
- mockall_double/src/lib.rs
There were a bunch of raw string literals in the unit tests.  I'm not sure why I used them; probably because of something to do with whitespace.  But they aren't necessary, and Clippy complains.
> Quiet clippy::needless_raw_string_hashes

- mockall/src/lib.rs
I think _name_ is more appropriate here since _namespace_ normally refers the grouping done by an `impl` blocks and modules.
> Clarify "namespace" to "name"

- mockall/tests/automock_rpitit.rs
In nightly compilers, it's now possible to return `impl Trait` in a trait method.  Mockall needs nothing new to support this.  The existing "deimplify" strategy, already used for inherent methods, works for trait methods too.
The generated code will still return `Box<dyn Trait>` instead of `impl Trait`.  We can't easily change that because the generated code also includes things like `Fn() -> impl Trait`, and Rust does not yet allow "impl Trait" as a return type for closures.  The generated code also includes things like `Into<impl Trait>`, which makes even less sense.
https://rust-lang.github.io/rfcs/3425-return-position-impl-trait-in-traits.html
> Add a test for the Return Position Impl Trait in Trait feature

- mockall/examples/synchronization.rs
- mockall/tests/automock_foreign_c.rs
- mockall/tests/automock_module.rs
- mockall/tests/mock_generic_struct_with_generic_static_method.rs
- mockall/tests/mock_struct_with_static_method.rs
Using a static method in two or more test cases requires synchronization, such as with a Mutex.  Previously we recommended adding a `let _m = SOME_MTX.lock().unwrap()` to the top of each such test case. But if one test case should fail, then the others will fail too due to a poisoned mutex.  It turns out that the `.unwrap()` is completely unnecessary; a poisoned Mutex still provides the necessary synchronization.  So simply remove all of the unwraps.
> Change the recommendation for static methods

- CHANGELOG.md
- mockall/tests/mock_concretize_with_bounds.rs
- mockall_derive/src/lib.rs
It's usually possible to turn such types into trait objects.  We just need to emit extra parenthesis in the generated code.
Fixes #530
> Fix using #[concretize] on functions with bounded generic types

- mockall/Cargo.toml
- mockall_derive/Cargo.toml
- mockall_double/Cargo.toml
Clarify that Mockall may be distributed under the terms of either the MIT or Apache-2.0 license.  This was always the intent, but was never expressed using the recommended SPDX syntax.
Fixes #529
> [skip ci] Clarify license terms

- CHANGELOG.md
- mockall/tests/raw_identifier.rs
- mockall_derive/src/lib.rs
- mockall_derive/src/mock_function.rs
This was a regression in 0.12.0, introduced by 60acf8e .
Fixes #533
> Fix mocking functions that use raw identifiers for their names.

- mockall/src/lib.rs
- mockall/tests/automock_generic_future.rs
- mockall/tests/automock_generic_future_with_where_clause.rs
- mockall/tests/automock_generic_struct.rs
- mockall/tests/automock_generic_struct_with_bounds.rs
- mockall/tests/automock_generic_struct_with_where_clause.rs
- mockall/tests/automock_generic_trait.rs
- mockall/tests/automock_generic_trait_with_bounds.rs
- mockall/tests/automock_generic_trait_with_where_clause.rs
- mockall/tests/automock_impl_generic_trait_for.rs
- mockall/tests/automock_impl_trait_for_generic.rs
- mockall/tests/automock_specializing_methods.rs
- mockall/tests/mock_concrete_struct_with_generic_trait.rs
- mockall/tests/mock_generic_constructor.rs
- mockall/tests/mock_generic_method_on_generic_struct_returning_nonstatic.rs
- mockall/tests/mock_generic_struct.rs
- mockall/tests/mock_generic_struct_with_bounds.rs
- mockall/tests/mock_generic_struct_with_generic_trait.rs
- mockall/tests/mock_generic_struct_with_generic_trait_with_different_bounds.rs
- mockall/tests/mock_generic_struct_with_nondefault_parameter.rs
- mockall/tests/mock_generic_struct_with_trait.rs
- mockall/tests/mock_generic_struct_with_trait_with_associated_types.rs
- mockall/tests/mock_generic_struct_with_where_clause.rs
- mockall/tests/mock_generic_struct_with_where_clause_and_trait.rs
- mockall/tests/mock_generic_trait.rs
- mockall/tests/mock_same_trait_twice_on_generic_struct.rs
- mockall/tests/mock_specializing_methods.rs
Mockall actually _can_ mock generic structs and traits with non-'static generic parameters.  The only thing it can't do is:
* generic methods with non-'static generic parameters
* generic structs and traits that have non-'static generic parameters and also have static methods.
I'm not sure at what point Mockall gained this ability.  Probably one of the several internal refactorings.
> Document generic parameters' lifetime requirements more precisely.

- CHANGELOG.md
- mockall/tests/clear_expectations_on_panic.rs
- mockall_derive/src/mock_function.rs
If a test case panics while holding a static method's internal Mutex locked, for example by violating a times() constraint, then clear the Mutex's poison during Drop.  We're going to delete all of its Expectations anyway, so there's no data to be poisoned.
Requires nightly.
Fixes #515
> Less Mutex poisoning

- CHANGELOG.md
- mockall/tests/automock_inline.rs
- mockall/tests/automock_must_use.rs
- mockall_derive/src/lib.rs
- mockall_derive/src/mock_function.rs
- mockall_derive/src/mock_item_struct.rs
- mockall_derive/src/mock_trait.rs
- mockall_derive/src/mockable_struct.rs
> Handle the #[inline], #[cold], and #[must_use] attributes

- mockall/src/lib.rs
`should_panic` doesn't accept an `expected` parameter for doc tests
(unlike unit tests).
Without this commit cargo doesn't recognise/render it as a doc test.
> Fix sequences doc test

- mockall/tests/automock_attrs.rs
- mockall/tests/cfg_attr_concretize.rs
- mockall/tests/mock_refmut_arguments.rs
- mockall_derive/build.rs
The latest rustc attempts to detect invalid `#[cfg()]` values.  But some of Mockall's tests conditionalize code on `target_os = "multics"` as an intentionally always-false condition.  Suppress the lint for those files.
> Fix unexpected_cfgs lints with the latest rustc

- mockall_derive/src/mock_function.rs
I tend to configure `Cargo.toml` with:
```toml
[workspace.lints.clippy]
indexing_slicing = "deny"
```
[https://rust-lang.github.io/rust-clippy/master/index.html#/indexing_slicing](https://rust-lang.github.io/rust-clippy/master/index.html#/indexing_slicing)
Among other lints to catch code that might panic. The generated code from `mockall` currently fails this lint, and it's difficult to add an exception for it with `#[allow()]` as it's occurring within a proc macro.
This PR updates codegen to replace the instance of index slicing with `.get().unwrap()`. This does not represent any real change in functionality, just passes the lint check now. It will still panic the same as it would have previously.
I am happy to change this to add a `#[allow()]` annotation in the generated code if this is …
> fix(mockall_derive): add allow(clippy::indexing_slicing) to generated module.

- mockall_derive/build.rs
Rust 1.71 and earlier ignored build script outputs like "cargo::name=value".  Rust nightly from around 5-May-2024 complains about unexpected_cfgs , and the suggested solution is to add a "cargo::name=value" output to the build script.  But intermediate Rust versions including 1.73.0 treat that syntax as an error.  Happily, all tested Rust versions accept and understand "cargo:name=value" (note the single colon).
This fixes a regression introduced by #574 and not yet released.
> Fix the build on Rust 1.73.0 and nearby versions

- .cirrus.yml
- CHANGELOG.md
- README.md
- mockall/Cargo.toml
- mockall/tests/automock_foreign_c.rs
- mockall/tests/automock_foreign_c_variadic.rs
- mockall_derive/src/mock_item.rs
Begining within Rust 1.81
(https://github.com/rust-lang/rust/issues/74990) Rust will abort when attempting to unwind a panic across an "extern C" boundary.  Previously it was technically UB, but it worked and Mockall relied on it.  Now, unwinding across such a boundary requires the "extern C-unwind" ABI. Use that ABI in the generated code.
However, don't use that ABI when mocking a C variadic function.  That doesn't work, due to https://github.com/rust-lang/rust/issues/126836 .
Fixes #584
> Use the C-unwind ABI instead of C when mocking extern C functions

- mockall/tests/automock_foreign_c_variadic.rs
- mockall_derive/src/mock_item.rs
Now that https://github.com/rust-lang/rust/issues/126836 is fixed.
> Use the C-unwind ABI when mocking variadic functions

- CHANGELOG.md
- mockall/Cargo.toml
- mockall/tests/auto_enum.rs
- mockall/tests/automock_impl_future.rs
- mockall_derive/src/lib.rs
Make Mockall compatible with the use of the auto_enums crate for functions that use RPIT, like this:
```rust
#[auto_enum(Future)]
fn foo() -> impl Future<Output=()> {
...
}
```
> Add compatibility with auto_enums

- mockall/tests/automock_concretize_closures.rs
- mockall_derive/src/lib.rs
- mockall_derive/src/mock_function.rs
FnMut arguments need two changes:
* Callbacks to methods like .returning() need a mutable reference to the
FnMut argument.
* The mock method needs a mutable binding for the FnMut argument
Fixes #577
> Make concretize work with FnMut arguments

- mockall/tests/automock_gat.rs
Now that our MSRV is 1.71.0
Fixes #436
> Enable the automock_gat test without the nightly feature

- CHANGELOG.md
- mockall/tests/mock_multiple_traits_same_name.rs
- mockall_derive/src/mock_trait.rs
An attempt to solve https://github.com/asomers/mockall/issues/600.
Not really sure about backward compatibility. Should be fine as we only change the generation of a private identifier. But it could cause issues if either a length limit is reached or a there's a name collision with a different ident.
> Support mocking multiple traits with same name

- mockall/tests/mock_docs.rs
Previously nightly compilers would ignore missing_docs in integration tests, but no more.
> Fix missing_docs lints with the latest nightly

- CHANGELOG.md
- mockall/tests/ref_option.rs
- mockall_derive/src/mock_function.rs
> Suppress the clippy::ref_option warning in generated code

- mockall_derive/src/lib.rs
- mockall_derive/src/mockable_struct.rs
If a struct has an elided lifetime in its impl block, then the generics list from the "impl" won't match the generics list from the struct. Mockall needs more work to handle that, and I'm not ready to invest that time right now.
> Better error message when mocking structs with elided lifetimes

- mockall_derive/src/mock_function.rs
Clippy's suggested fix requires a 1.82.0 MSRV.  So for now, merely suppress it.
Issue #628
> Suppress a new clippy::unnecessary-map-or warning

- mockall_derive/src/mock_function.rs
As this crate is a proc macro, the code was generating a formatting string to emit in the generated code.  So the warning is a false alarm.
> Quiet a clippy::literal_string_with_formatting_args warning

- CHANGELOG.md
- mockall/tests/mock_life0.rs
- mockall/tests/single-use-lifetime.rs
- mockall_derive/src/mock_function.rs
> Suppress `single-use-lifetimes` warnings in generated code

- mockall_derive/src/lib.rs
See also https://github.com/rust-lang/rust-clippy/discussions/14256
> Suppress an unhelpful clippy lint.

- .cirrus.yml
- CHANGELOG.md
- README.md
- mockall/Cargo.toml
- mockall_derive/src/mock_function.rs
Even when using a stable Rust compiler.  This raises MSRV to 1.77.0.
> No longer poison a Context object's internal `Mutex` when panicing

- CHANGELOG.md
- mockall/src/lib.rs
- mockall/tests/clear_expectations_on_panic.rs
- mockall/tests/mock_read.rs
- mockall_derive/src/mock_function.rs
std::io::Read::read is often called with an uninitialized buffer as its argument.  So Mockall shouldn't try to read from that buffer, even though the language rules allow it to.  Previously, Mockall would try to read from it, in order to format a panic message in case no matching Expectation was found.
Now, Mockall will not try to format such a panic message preemptively. It will only do it if there actually isn't any matching Expectation. That also provides a small performance boost to all users.
Also, do a better job of clearing poison from static methods' Mutexes following a panic.  Previously we would only do that if the user had created a Context object.  Now we will do it regardless.
Fixes #647
> Better support for mocking methods like std::io::Read::read

- mockall/Cargo.toml
- mockall/build.rs
- mockall/tests/automock_attrs.rs
- mockall/tests/cfg_attr_concretize.rs
Rather than disabling the unexpected-cfg lint.
Fixes #573
> Make use of cargo::rustc-check-cfg
