asomers/mockall

mockall/src/lib.rs
mockall/tests/automock_return_owned.rs
mockall/tests/mock_generic_struct_with_generic_static_method.rs
mockall/tests/mock_generic_struct_with_nondefault_parameter.rs
mockall/tests/mock_reference_arguments.rs
mockall/tests/mock_return_mutable_reference.rs
mockall/tests/mock_return_reference.rs
mockall/tests/mock_struct.rs
mockall/tests/mock_struct_with_static_method.rs
mockall_derive/src/expectation.rs

More descriptive panic messages for several different types of panic.  This should hopefully make failures easier to debug.

Better panics

---

CHANGELOG.md
mockall/tests/automock_module.rs
mockall_derive/src/automock.rs

Fix automocking modules that contain use statements

---

mockall/src/lib.rs

micro-micro edits

---

mockall/src/lib.rs

Hide fewer use statements during doc tests

---

mockall/tests/mock_impl_generic_trait.rs
mockall_derive/src/lib.rs

The regression was probably introduced by PR #86

Fix regression mocking "impl trait" for generic traits

---

README.md

in the README, show usage as a dev-dependency

---

CHANGELOG.md
mockall/tests/mock_life0.rs
mockall_derive/src/lib.rs

Fix mocking methods with an explicit receiver lifetime

---

mockall_derive/src/mock.rs

Diff reduction between a structure's checkpoint method and its
substructure's.

Minor internal refactor.

---

mockall/tests/mock_generic_method_returning_nonstatic.rs

Also, add comments explaining why certain related cases don't work.

Add a test case for a method returning a reference to nonstatic data

---

mockall_derive/src/automock.rs
mockall_derive/src/lib.rs
mockall_derive/src/mock_function.rs
mockall_derive/src/mock_item_struct.rs
mockall_derive/src/mockable_item.rs
mockall_derive/src/mockable_struct.rs

Several more changes that mostly aren't user-visible.  The only ones that are are changes that improve compile-time error messages.

Minor refactor 7

---

README.md

Just in case anyone else makes the same mistake: https://github.com/asomers/mockall/issues/171.

Add program namespace to test module example

---

mockall/tests/mock_return_anonymous_lifetime.rs
mockall_derive/src/lib.rs
mockall_derive/src/mockable_struct.rs

Support mocking methods that return types including anonymous lifetimes

---

mockall_derive/src/lib.rs

Make the unit tests more resilient to whitespace generated by
proc-macro2.  The particular breakage was caused by that crate's commit 4101b0ca52a96a4a290cda9bed46bbeafcdcbac0

Fix unit tests with proc-macro2 1.0.20

---

mockall_derive/src/lib.rs
mockall_derive/src/mockable_struct.rs

Mockall does not support "impl Trait" arguments.  It would theoretically
be possible to do so, but the effort would not justify the reward, IMHO.
A method like `fn foo(x: impl T)` can equivalently be written as
`fn foo<Q: T>(x: Q)`, so it's very easy for a user to work around this
limitation.
Fixes #209

Emit a better error message for "impl Trait" arguments

---

mockall_derive/src/mock_item_struct.rs

Clippy default_trait_access warning fix

---

.cirrus.yml

Now that https://github.com/rust-lang/rust/issues/78660 is fixed

Revert 5926def2a58d60c3d63a109926a1498779c35744.

---

mockall_derive/src/automock.rs
mockall_derive/src/lib.rs
mockall_derive/src/mockable_struct.rs

Elaborate the error message for mocking Fn trait objects

---

mockall/src/lib.rs

Wordsmith the docs for the new method

---

.cirrus.yml

Suppress a buggy Clippy lint

---

CHANGELOG.md
mockall/Cargo.toml
mockall_derive/Cargo.toml

- https://github.com/asomers/mockall/pull/317
Sorry, I think I need to practice git :(
Signed-off-by: Chojan Shang <psiace@outlook.com>

Bump out-of-date deps

---

.cirrus.yml

Combine the nightly test task with the clippy and minver tasks into a
single task

Reduce the number of cirrus tasks

---

mockall/src/lib.rs

i was questioning how to mock `#[derive(Clone)]` and saw there were a few issues with people wondering the same thing. hopefully this clears up future questions

docs: add some docs about using mock! to mock clone derives

---

mockall/Cargo.toml
mockall_derive/Cargo.toml
mockall_derive/src/automock.rs
mockall_derive/src/lib.rs
mockall_derive/src/mock_function.rs
mockall_derive/src/mock_item_struct.rs
mockall_derive/src/mock_trait.rs
mockall_derive/src/mockable_item.rs
mockall_derive/src/mockable_struct.rs
mockall_double/Cargo.toml

This requires many changes to the proc macro, but no changes should be visible to the user.

Use syn-2.0.0

---

mockall_derive/Cargo.toml
mockall_double/Cargo.toml

https://github.com/rust-lang/rust/issues/113152

Fix build with latest nightly and -Zminimal-versions

---

.cirrus.yml

This might speed up checking out the cache?

CI: add a fingerprint_script to the cargo_cache directive

---

mockall/tests/automock_foreign_c_variadic.rs

Don't add miri to CI yet, because I'm not convinced that it would have any benefits for this crate.

Fix running the tests with miri

---

mockall/tests/automock_impl_trait_with_associated_types_for.rs
mockall/tests/automock_unsafe_trait.rs

Fix some dead_code warnings with the latest compiler

---

mockall/src/lib.rs
mockall/tests/automock_generic_future_with_where_clause.rs
mockall/tests/raw_identifier.rs

* fix doc_lazy_continuation lints
* dead code

Pacify Clippy

---

mockall/tests/automock_generic_future.rs
mockall/tests/automock_impl_trait.rs
mockall/tests/automock_module.rs
mockall/tests/mock_impl_trait.rs

* unused_must_use from format!
* dead_code on a non-pub struct

Clippy cleanup in the tests

---

CHANGELOG.md
mockall_derive/src/lib.rs

During declosurefy, make sure to include additional trait bounds
